from user import *
user_one = User('Ben', 2, 4 )
user_two = User('Carlan', 1, 0)
print(user_one)
print(user_two)
user_one.give_a_taco(user_two)
print(user_one)
print(user_two)
user_one.give_a_taco(user_two)
print(user_one)
print(user_two)
user_one.give_a_taco(user_two)
print(user_one)
print(user_two)